network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
    eth1:
      dhcp4: false
      addresses:
        - 10.100.10.1/24
      routes:
        - to: 10.100.11.0/24
          via: 10.100.10.2/24
